# Generated by Django 4.0.3 on 2022-03-18 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp', models.SmallIntegerField(default=0)),
                ('name', models.CharField(max_length=64)),
                ('campaign', models.CharField(blank=True, max_length=64, null=True)),
                ('str', models.SmallIntegerField(default=0)),
                ('dex', models.SmallIntegerField(default=0)),
                ('con', models.SmallIntegerField(default=0)),
                ('int', models.SmallIntegerField(default=0)),
                ('wis', models.SmallIntegerField(default=0)),
                ('cha', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Classs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('skillPoints', models.PositiveSmallIntegerField()),
                ('HD', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('armorType', models.CharField(blank=True, max_length=10)),
                ('armorBonus', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('shieldBonus', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ACP', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ASF', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('maxDex', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('weaponType', models.CharField(blank=True, max_length=10, null=True)),
                ('weaponUsage', models.CharField(blank=True, max_length=10, null=True)),
                ('mediumDamage', models.CharField(blank=True, max_length=10, null=True)),
                ('mediumWeight', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('finesse', models.BooleanField(blank=True, null=True)),
                ('reach', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('range', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('damageType', models.CharField(blank=True, max_length=10, null=True)),
                ('special', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('description', models.TextField(max_length=511)),
                ('strPR', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('dexPR', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('conPR', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('intPR', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('wisPR', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('chaPR', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fortPR', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('refPR', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('willPR', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('babPR', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('classLevelPR', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('classPR', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='HeroForgeApi.classs')),
                ('feat1PR', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='HeroForgeApi.feat')),
                ('feat2PR', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='HeroForgeApi.feat')),
                ('feat3PR', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='HeroForgeApi.feat')),
                ('feat4PR', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='HeroForgeApi.feat')),
            ],
        ),
        migrations.CreateModel(
            name='FeatOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeroForgeApi.feat')),
            ],
        ),
        migrations.CreateModel(
            name='FeatSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('featOptions', models.ManyToManyField(through='HeroForgeApi.FeatOption', to='HeroForgeApi.feat')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characterLevel', models.PositiveSmallIntegerField()),
                ('HDRoll', models.PositiveSmallIntegerField(default=0)),
                ('statIncrease', models.CharField(blank=True, max_length=3, null=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeroForgeApi.character')),
                ('classs', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='HeroForgeApi.classs')),
                ('feat', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='HeroForgeApi.feat')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('trainedOnly', models.BooleanField(default=False)),
                ('multiType', models.SmallIntegerField()),
                ('attribute', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('racialBonus', models.CharField(blank=True, max_length=55)),
                ('racialPenalty', models.CharField(blank=True, max_length=55)),
                ('special', models.CharField(blank=True, max_length=55)),
                ('speed', models.CharField(max_length=55)),
                ('altSpeedType', models.CharField(blank=True, max_length=55)),
                ('altSpeed', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('feat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='HeroForgeApi.feat')),
                ('featSet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='HeroForgeApi.featset')),
            ],
        ),
        migrations.CreateModel(
            name='Proficiency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=10)),
                ('sourceId', models.PositiveSmallIntegerField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeroForgeApi.character')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeroForgeApi.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='LevelSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveSmallIntegerField(default=0)),
                ('multiTypeName', models.CharField(blank=True, max_length=3)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeroForgeApi.level')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeroForgeApi.skill')),
            ],
        ),
        migrations.AddField(
            model_name='level',
            name='levelSkills',
            field=models.ManyToManyField(through='HeroForgeApi.LevelSkill', to='HeroForgeApi.skill'),
        ),
        migrations.AddField(
            model_name='featoption',
            name='featSet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeroForgeApi.featset'),
        ),
        migrations.CreateModel(
            name='Equipped',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeroForgeApi.character')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeroForgeApi.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='ClassSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BooleanField()),
                ('classs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeroForgeApi.classs')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeroForgeApi.skill')),
            ],
        ),
        migrations.AddField(
            model_name='classs',
            name='classSkills',
            field=models.ManyToManyField(through='HeroForgeApi.ClassSkill', to='HeroForgeApi.skill'),
        ),
        migrations.CreateModel(
            name='ClassLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField()),
                ('features', models.TextField()),
                ('BAB', models.PositiveSmallIntegerField()),
                ('Fort', models.PositiveSmallIntegerField()),
                ('Ref', models.PositiveSmallIntegerField()),
                ('Will', models.PositiveSmallIntegerField()),
                ('classs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levelDetails', to='HeroForgeApi.classs')),
                ('featSet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='HeroForgeApi.featset')),
                ('fixedFeat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='HeroForgeApi.feat')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterFeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specificOption', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('optionSource', models.CharField(blank=True, max_length=20)),
                ('source', models.CharField(max_length=20)),
                ('sourceId', models.PositiveSmallIntegerField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeroForgeApi.character')),
                ('feat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeroForgeApi.feat')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='equipment',
            field=models.ManyToManyField(through='HeroForgeApi.Equipped', to='HeroForgeApi.equipment'),
        ),
        migrations.AddField(
            model_name='character',
            name='proficiencies',
            field=models.ManyToManyField(related_name='Proficiencies', through='HeroForgeApi.Proficiency', to='HeroForgeApi.equipment'),
        ),
        migrations.AddField(
            model_name='character',
            name='race',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='HeroForgeApi.race'),
        ),
        migrations.AddField(
            model_name='character',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
