# Generated by Django 4.0.3 on 2022-03-15 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HeroForgeApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField()),
                ('features', models.TextField()),
                ('BAB', models.PositiveSmallIntegerField()),
                ('Fort', models.PositiveSmallIntegerField()),
                ('Ref', models.PositiveSmallIntegerField()),
                ('Will', models.PositiveSmallIntegerField()),
                ('classId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeroForgeApi.classs')),
                ('featSetId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='HeroForgeApi.featset')),
                ('fixedFeat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='HeroForgeApi.feat')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterFeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specificOption', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('optionSource', models.CharField(max_length=20)),
                ('source', models.CharField(max_length=20)),
                ('sourceId', models.PositiveSmallIntegerField()),
                ('characterId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeroForgeApi.character')),
                ('featId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeroForgeApi.feat')),
            ],
        ),
    ]
