# Generated by Django 4.0.3 on 2022-03-23 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HeroForgeApi', '0002_level_classfeat_level_leveldetails_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classskill',
            name='classs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skillProficiency', to='HeroForgeApi.classs'),
        ),
        migrations.AlterField(
            model_name='feat',
            name='babPR',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='feat',
            name='chaPR',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='feat',
            name='classLevelPR',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='feat',
            name='classPR',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='HeroForgeApi.classs'),
        ),
        migrations.AlterField(
            model_name='feat',
            name='conPR',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='feat',
            name='dexPR',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='feat',
            name='feat1PR',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='HeroForgeApi.feat'),
        ),
        migrations.AlterField(
            model_name='feat',
            name='feat2PR',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='HeroForgeApi.feat'),
        ),
        migrations.AlterField(
            model_name='feat',
            name='feat3PR',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='HeroForgeApi.feat'),
        ),
        migrations.AlterField(
            model_name='feat',
            name='feat4PR',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='HeroForgeApi.feat'),
        ),
        migrations.AlterField(
            model_name='feat',
            name='fortPR',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='feat',
            name='intPR',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='feat',
            name='refPR',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='feat',
            name='strPR',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='feat',
            name='willPR',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='feat',
            name='wisPR',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='levelskill',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skillAssignment', to='HeroForgeApi.level'),
        ),
    ]
