# Generated by Django 4.0.3 on 2022-03-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeroForgeApi', '0002_classlevel_characterfeat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='mediumWeight',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
