# Generated by Django 4.0.3 on 2022-03-15 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeroForgeApi', '0003_alter_equipment_mediumweight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=32),
        ),
    ]
