# Generated by Django 4.0.3 on 2022-03-23 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HeroForgeApi', '0003_alter_classskill_classs_alter_feat_babpr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proficient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='classlevel',
            name='classProficiency',
            field=models.ManyToManyField(blank=True, null=True, through='HeroForgeApi.Proficient', to='HeroForgeApi.equipment'),
        ),
        migrations.AlterField(
            model_name='characterfeat',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learnedFeats', to='HeroForgeApi.character'),
        ),
        migrations.AddField(
            model_name='proficient',
            name='classLevel',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='HeroForgeApi.classlevel'),
        ),
        migrations.AddField(
            model_name='proficient',
            name='equipment',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='HeroForgeApi.equipment'),
        ),
        migrations.AddField(
            model_name='proficient',
            name='race',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='HeroForgeApi.race'),
        ),
    ]
