# Generated by Django 4.0.3 on 2022-03-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeroForgeApi', '0004_proficient_classlevel_classproficiency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='racialProficiency',
            field=models.ManyToManyField(blank=True, null=True, through='HeroForgeApi.Proficient', to='HeroForgeApi.equipment'),
        ),
    ]
