# Generated by Django 4.0.3 on 2022-03-23 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeroForgeApi', '0005_race_racialproficiency'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipped',
            name='slot',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
