# Generated by Django 4.0.3 on 2022-03-17 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HeroForgeApi', '0007_alter_skill_trainedonly'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='raceId',
            new_name='race',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='userId',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='characterfeat',
            old_name='characterId',
            new_name='character',
        ),
        migrations.RenameField(
            model_name='characterfeat',
            old_name='featId',
            new_name='feat',
        ),
        migrations.RenameField(
            model_name='classskill',
            old_name='classId',
            new_name='classs',
        ),
        migrations.RenameField(
            model_name='classskill',
            old_name='skillId',
            new_name='skill',
        ),
        migrations.RenameField(
            model_name='equipped',
            old_name='characterId',
            new_name='character',
        ),
        migrations.RenameField(
            model_name='equipped',
            old_name='equipmentId',
            new_name='equipment',
        ),
        migrations.RenameField(
            model_name='featoption',
            old_name='featId',
            new_name='feat',
        ),
        migrations.RenameField(
            model_name='featoption',
            old_name='featSetId',
            new_name='featSet',
        ),
        migrations.RenameField(
            model_name='level',
            old_name='characterId',
            new_name='character',
        ),
        migrations.RenameField(
            model_name='level',
            old_name='classId',
            new_name='classs',
        ),
        migrations.RenameField(
            model_name='levelskill',
            old_name='levelId',
            new_name='level',
        ),
        migrations.RenameField(
            model_name='levelskill',
            old_name='skillId',
            new_name='skill',
        ),
        migrations.RenameField(
            model_name='proficiency',
            old_name='characterId',
            new_name='character',
        ),
        migrations.RenameField(
            model_name='proficiency',
            old_name='equipmentId',
            new_name='equipment',
        ),
        migrations.RenameField(
            model_name='race',
            old_name='featId',
            new_name='feat',
        ),
        migrations.RenameField(
            model_name='race',
            old_name='featSetId',
            new_name='featSet',
        ),
    ]
