# Generated by Django 4.0.3 on 2022-03-17 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HeroForgeApi', '0008_rename_raceid_character_race_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classlevel',
            old_name='classId',
            new_name='classs',
        ),
        migrations.RenameField(
            model_name='classlevel',
            old_name='featSetId',
            new_name='featSet',
        ),
    ]
